### ISSUE TITLE
Too many shift while reading raw pressure

### ISSUE THREAD

**Issue by gabbla** [STMicroelectronics/lps27hhw-pid#1]
Hello,

while reading the pressure through `lps27hhw_pressure_raw_get` an extra shift is performed at the end (line 681).

https://github.com/STMicroelectronics/lps27hhw/blob/8b974831885dd9b7af4a63d36bdb9a9fc16367ad/lps27hhw_reg.c#L672-L684

Edit for future readers: `n << 8` equals `n * 256`.

Example: 
If `reg[3] = {0xCC, 0x43, 0x3F}` (where `reg[0]` is XL byte, `reg[1]` LSB byte and `reg[2]` MSB) the expected `buff` value is `0x003F43CC` and **not** `0x3F43CC00`.

In fact:
- 0x003F43CC / 4096 = 1012.24 HPa
- 0x3F43CC00 / 4096 = 259132.75 HPa

I can open a pull request if needed.

Thank you,
Gab

**Comment by albezanc** [comment]
Hi gabbia, in order to keep the same logic of other devices (32 bit raw data format left aligned), this issues impact the function `lps27hhw_from_lsb_to_hpa`.

Thanks very much for your contribution!
